package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name = "cita", catalog = "clinicadb")
public class Cita implements java.io.Serializable ,  Comparable<Cita> {

	private Integer citaId;
	private Enfermera enfermera;
	private NotaVenta notaVenta;
	private Paciente paciente;
	private Date fecha;
	private Date hora;
	private String consulta;
	private String status;
	private byte[] observaciones;
	private Set<Tratamiento> tratamientos = new HashSet<Tratamiento>(0);

	public Cita() {
	}

	public Cita(NotaVenta notaVenta, Paciente paciente) {
		this.notaVenta = notaVenta;
		this.paciente = paciente;
	}

	public Cita(Enfermera enfermera, NotaVenta notaVenta, Paciente paciente, Date fecha, Date hora, String consulta,
			String status, byte[] observaciones, Set<Tratamiento> tratamientos) {
		this.enfermera = enfermera;
		this.notaVenta = notaVenta;
		this.paciente = paciente;
		this.fecha = fecha;
		this.hora = hora;
		this.consulta = consulta;
		this.status = status;
		this.observaciones = observaciones;
		this.tratamientos = tratamientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cita_id", unique = true, nullable = false)
	public Integer getCitaId() {
		return this.citaId;
	}

	public void setCitaId(Integer citaId) {
		this.citaId = citaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enfermera_id")
	public Enfermera getEnfermera() {
		return this.enfermera;
	}

	public void setEnfermera(Enfermera enfermera) {
		this.enfermera = enfermera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nota_venta_id", nullable = false)
	public NotaVenta getNotaVenta() {
		return this.notaVenta;
	}

	public void setNotaVenta(NotaVenta notaVenta) {
		this.notaVenta = notaVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paciente_id", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "consulta", length = 45)
	public String getConsulta() {
		return this.consulta;
	}

	public void setConsulta(String consulta) {
		this.consulta = consulta;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "observaciones")
	public byte[] getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(byte[] observaciones) {
		this.observaciones = observaciones;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "cita_has_tratamiento", catalog = "clinicadb", joinColumns = {
			@JoinColumn(name = "cita_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "tratamiento_id", nullable = false, updatable = false) })
	public Set<Tratamiento> getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set<Tratamiento> tratamientos) {
		this.tratamientos = tratamientos;
	}
	
	
	@Override
	public int compareTo(Cita o) {
		// TODO Auto-generated method stub
		return this.hora.compareTo(o.getHora());
	}

}
