package com.sanantial.entity;

// Generated Feb 3, 2014 12:35:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consulta generated by hbm2java
 */
@Entity
@Table(name = "consulta", catalog = "sanantialdb")
public class Consulta implements java.io.Serializable {

	private Integer consultaId;
	private Doctor doctor;
	private String consultaNombre;
	private Long precio;
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);

	public Consulta() {
	}

	public Consulta(Doctor doctor) {
		this.doctor = doctor;
	}

	public Consulta(Doctor doctor, String consultaNombre, Long precio,
			Set<VentaDiaria> ventaDiarias) {
		this.doctor = doctor;
		this.consultaNombre = consultaNombre;
		this.precio = precio;
		this.ventaDiarias = ventaDiarias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consulta_id", unique = true, nullable = false)
	public Integer getConsultaId() {
		return this.consultaId;
	}

	public void setConsultaId(Integer consultaId) {
		this.consultaId = consultaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@Column(name = "consulta_nombre", length = 45)
	public String getConsultaNombre() {
		return this.consultaNombre;
	}

	public void setConsultaNombre(String consultaNombre) {
		this.consultaNombre = consultaNombre;
	}

	@Column(name = "precio", precision = 10, scale = 0)
	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consulta")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

}
