package com.sanantial.entity;

// Generated 12/11/2013 12:25:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "sanantialdb")
public class Doctor implements java.io.Serializable {

	private Integer doctorId;
	private String doctorNombre;
	private Boolean activo;
	
	public Doctor() {
	}

	public Doctor(String doctorNombre, Boolean activo, Set<Citas> citases) {
		this.doctorNombre = doctorNombre;
		this.activo = activo;
		//this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doctor_id", unique = true, nullable = false)
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_nombre", length = 45)
	public String getDoctorNombre() {
		return this.doctorNombre;
	}

	public void setDoctorNombre(String doctorNombre) {
		this.doctorNombre = doctorNombre;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
//	public Set<Citas> getCitases() {
//		return this.citases;
//	}
//
//	public void setCitases(Set<Citas> citases) {
//		this.citases = citases;
//	}

}
