package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "clinicadb")
public class Doctor implements java.io.Serializable {

	private Integer doctorId;
	private String doctorNombre;
	private Boolean activo;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Doctor() {
	}

	public Doctor(String doctorNombre, Boolean activo, Set<Consulta> consultas) {
		this.doctorNombre = doctorNombre;
		this.activo = activo;
		this.consultas = consultas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "doctor_id", unique = true, nullable = false)
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_nombre", length = 45)
	public String getDoctorNombre() {
		return this.doctorNombre;
	}

	public void setDoctorNombre(String doctorNombre) {
		this.doctorNombre = doctorNombre;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
