package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enfermera generated by hbm2java
 */
@Entity
@Table(name = "enfermera", catalog = "clinicadb")
public class Enfermera implements java.io.Serializable {

	private Integer enfermeraId;
	private String enfermeraNombre;
	private Boolean activa;
	private Set<Cita> citas = new HashSet<Cita>(0);

	public Enfermera() {
	}

	public Enfermera(String enfermeraNombre, Boolean activa, Set<Cita> citas) {
		this.enfermeraNombre = enfermeraNombre;
		this.activa = activa;
		this.citas = citas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "enfermera_id", unique = true, nullable = false)
	public Integer getEnfermeraId() {
		return this.enfermeraId;
	}

	public void setEnfermeraId(Integer enfermeraId) {
		this.enfermeraId = enfermeraId;
	}

	@Column(name = "enfermera_nombre", length = 45)
	public String getEnfermeraNombre() {
		return this.enfermeraNombre;
	}

	public void setEnfermeraNombre(String enfermeraNombre) {
		this.enfermeraNombre = enfermeraNombre;
	}

	@Column(name = "activa")
	public Boolean getActiva() {
		return this.activa;
	}

	public void setActiva(Boolean activa) {
		this.activa = activa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermera")
	public Set<Cita> getCitas() {
		return this.citas;
	}

	public void setCitas(Set<Cita> citas) {
		this.citas = citas;
	}

}
