package com.sanantial.entity;

// Generated 12/11/2013 12:25:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enfermera generated by hbm2java
 */
@Entity
@Table(name = "enfermera", catalog = "sanantialdb")
public class Enfermera implements java.io.Serializable {

	private Integer enfermeraId;
	private String enfermeraNombre;
	private Boolean activa;
	private Set<Citas> citases = new HashSet<Citas>(0);

	public Enfermera() {
	}

	public Enfermera(String enfermeraNombre, Boolean activa, Set<Citas> citases) {
		this.enfermeraNombre = enfermeraNombre;
		this.activa = activa;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "enfermera_id", unique = true, nullable = false)
	public Integer getEnfermeraId() {
		return this.enfermeraId;
	}

	public void setEnfermeraId(Integer enfermeraId) {
		this.enfermeraId = enfermeraId;
	}

	@Column(name = "enfermera_nombre", length = 45)
	public String getEnfermeraNombre() {
		return this.enfermeraNombre;
	}

	public void setEnfermeraNombre(String enfermeraNombre) {
		this.enfermeraNombre = enfermeraNombre;
	}

	@Column(name = "activa")
	public Boolean getActiva() {
		return this.activa;
	}

	public void setActiva(Boolean activa) {
		this.activa = activa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermera")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}

}
