package com.sanantial.entity;

// Generated Jan 11, 2014 3:42:07 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gasto generated by hbm2java
 */
@Entity
@Table(name = "gasto", catalog = "sanantialdb")
public class Gasto implements java.io.Serializable {

	private Integer gastoId;
	private String conceptoGasto;
	private Long totalGasto;
	private Set<GastoDiario> gastoDiarios = new HashSet<GastoDiario>(0);

	public Gasto() {
	}

	public Gasto(String conceptoGasto, Long totalGasto,
			Set<GastoDiario> gastoDiarios) {
		this.conceptoGasto = conceptoGasto;
		this.totalGasto = totalGasto;
		this.gastoDiarios = gastoDiarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gasto_id", unique = true, nullable = false)
	public Integer getGastoId() {
		return this.gastoId;
	}

	public void setGastoId(Integer gastoId) {
		this.gastoId = gastoId;
	}

	@Column(name = "concepto_gasto", length = 45)
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "total_gasto", precision = 10, scale = 0)
	public Long getTotalGasto() {
		return this.totalGasto;
	}

	public void setTotalGasto(Long totalGasto) {
		this.totalGasto = totalGasto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gasto")
	public Set<GastoDiario> getGastoDiarios() {
		return this.gastoDiarios;
	}

	public void setGastoDiarios(Set<GastoDiario> gastoDiarios) {
		this.gastoDiarios = gastoDiarios;
	}

}
