package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Habitacion generated by hbm2java
 */
@Entity
@Table(name = "habitacion", catalog = "clinicadb")
public class Habitacion implements java.io.Serializable {

	private int habitacionId;
	private String descripcion;
	private Set<HabitacionNota> habitacionNotas = new HashSet<HabitacionNota>(0);

	public Habitacion() {
	}

	public Habitacion(int habitacionId) {
		this.habitacionId = habitacionId;
	}

	public Habitacion(int habitacionId, String descripcion, Set<HabitacionNota> habitacionNotas) {
		this.habitacionId = habitacionId;
		this.descripcion = descripcion;
		this.habitacionNotas = habitacionNotas;
	}

	@Id

	@Column(name = "habitacion_id", unique = true, nullable = false)
	public int getHabitacionId() {
		return this.habitacionId;
	}

	public void setHabitacionId(int habitacionId) {
		this.habitacionId = habitacionId;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitacion")
	public Set<HabitacionNota> getHabitacionNotas() {
		return this.habitacionNotas;
	}

	public void setHabitacionNotas(Set<HabitacionNota> habitacionNotas) {
		this.habitacionNotas = habitacionNotas;
	}

}
