package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HabitacionNota generated by hbm2java
 */
@Entity
@Table(name = "habitacion_nota", catalog = "clinicadb")
public class HabitacionNota implements java.io.Serializable {

	private int habitacionNotaId;
	private Consulta consulta;
	private Habitacion habitacion;
	private Insumo insumo;
	private Medicamento medicamento;
	private Paciente paciente;
	private Tratamiento tratamiento;
	private String observaciones;

	public HabitacionNota() {
	}

	public HabitacionNota(int habitacionNotaId, Habitacion habitacion, Paciente paciente) {
		this.habitacionNotaId = habitacionNotaId;
		this.habitacion = habitacion;
		this.paciente = paciente;
	}

	public HabitacionNota(int habitacionNotaId, Consulta consulta, Habitacion habitacion, Insumo insumo,
			Medicamento medicamento, Paciente paciente, Tratamiento tratamiento, String observaciones) {
		this.habitacionNotaId = habitacionNotaId;
		this.consulta = consulta;
		this.habitacion = habitacion;
		this.insumo = insumo;
		this.medicamento = medicamento;
		this.paciente = paciente;
		this.tratamiento = tratamiento;
		this.observaciones = observaciones;
	}

	@Id

	@Column(name = "habitacion_nota_id", unique = true, nullable = false)
	public int getHabitacionNotaId() {
		return this.habitacionNotaId;
	}

	public void setHabitacionNotaId(int habitacionNotaId) {
		this.habitacionNotaId = habitacionNotaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consulta_id")
	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "habitacion_id", nullable = false)
	public Habitacion getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(Habitacion habitacion) {
		this.habitacion = habitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insumos_id")
	public Insumo getInsumo() {
		return this.insumo;
	}

	public void setInsumo(Insumo insumo) {
		this.insumo = insumo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicamento_id")
	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paciente_id", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tratamiento_id")
	public Tratamiento getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(Tratamiento tratamiento) {
		this.tratamiento = tratamiento;
	}

	@Column(name = "observaciones", length = 45)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
