package com.sanantial.entity;

// Generated Jan 11, 2014 3:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IngresoDiario generated by hbm2java
 */
@Entity
@Table(name = "ingreso_diario", catalog = "sanantialdb")
public class IngresoDiario implements java.io.Serializable {

	private Integer ingresoDiarioId;
	private Usuario usuario;
	private Ingreso ingreso;
	private Date fecha;

	public IngresoDiario() {
	}

	public IngresoDiario(Usuario usuario, Ingreso ingreso) {
		this.usuario = usuario;
		this.ingreso = ingreso;
	}

	public IngresoDiario(Usuario usuario, Ingreso ingreso, Date fecha) {
		this.usuario = usuario;
		this.ingreso = ingreso;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ingreso_diario_id", unique = true, nullable = false)
	public Integer getIngresoDiarioId() {
		return this.ingresoDiarioId;
	}

	public void setIngresoDiarioId(Integer ingresoDiarioId) {
		this.ingresoDiarioId = ingresoDiarioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingreso_id", nullable = false)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
