package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Insumo generated by hbm2java
 */
@Entity
@Table(name = "insumo", catalog = "clinicadb")
public class Insumo implements java.io.Serializable {

	private int insumoId;
	private String descripcion;
	private Long precio;
	private Set<HabitacionNota> habitacionNotas = new HashSet<HabitacionNota>(0);

	public Insumo() {
	}

	public Insumo(int insumoId) {
		this.insumoId = insumoId;
	}

	public Insumo(int insumoId, String descripcion, Long precio, Set<HabitacionNota> habitacionNotas) {
		this.insumoId = insumoId;
		this.descripcion = descripcion;
		this.precio = precio;
		this.habitacionNotas = habitacionNotas;
	}

	@Id

	@Column(name = "insumo_id", unique = true, nullable = false)
	public int getInsumoId() {
		return this.insumoId;
	}

	public void setInsumoId(int insumoId) {
		this.insumoId = insumoId;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio", precision = 10, scale = 0)
	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "insumo")
	public Set<HabitacionNota> getHabitacionNotas() {
		return this.habitacionNotas;
	}

	public void setHabitacionNotas(Set<HabitacionNota> habitacionNotas) {
		this.habitacionNotas = habitacionNotas;
	}

}
