package com.sanantial.entity;

// Generated Jan 11, 2014 3:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaVenta generated by hbm2java
 */
@Entity
@Table(name = "nota_venta", catalog = "sanantialdb")
public class NotaVenta implements java.io.Serializable {

	private Integer notaVentaId;
	private Date fecha;
	private Boolean pagada;
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);
	private Set<Citas> citases = new HashSet<Citas>(0);

	public NotaVenta() {
	}

	public NotaVenta(Date fecha, Set<VentaDiaria> ventaDiarias,
			Set<Citas> citases) {
		this.fecha = fecha;
		this.ventaDiarias = ventaDiarias;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nota_venta_id", unique = true, nullable = false)
	public Integer getNotaVentaId() {
		return this.notaVentaId;
	}

	public void setNotaVentaId(Integer notaVentaId) {
		this.notaVentaId = notaVentaId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaVenta")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaVenta")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}
	
	@Column(name = "pagada")
	public Boolean getPagada() {
		return this.pagada;
	}

	public void setPagada(Boolean pagada) {
		this.pagada = pagada;
	}

}
