package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaVenta generated by hbm2java
 */
@Entity
@Table(name = "nota_venta", catalog = "clinicadb")
public class NotaVenta implements java.io.Serializable {

	private Integer notaVentaId;
	private Date fecha;
	private Boolean pagada;
	private Set<Cita> citas = new HashSet<Cita>(0);
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);

	public NotaVenta() {
	}

	public NotaVenta(Date fecha, Boolean pagada, Set<Cita> citas, Set<VentaDiaria> ventaDiarias) {
		this.fecha = fecha;
		this.pagada = pagada;
		this.citas = citas;
		this.ventaDiarias = ventaDiarias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nota_venta_id", unique = true, nullable = false)
	public Integer getNotaVentaId() {
		return this.notaVentaId;
	}

	public void setNotaVentaId(Integer notaVentaId) {
		this.notaVentaId = notaVentaId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "pagada")
	public Boolean getPagada() {
		return this.pagada;
	}

	public void setPagada(Boolean pagada) {
		this.pagada = pagada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaVenta")
	public Set<Cita> getCitas() {
		return this.citas;
	}

	public void setCitas(Set<Cita> citas) {
		this.citas = citas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaVenta")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

}
