package com.sanantial.entity;

// Generated 8/07/2014 07:40:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", catalog = "sanantialdb")
public class Paciente implements java.io.Serializable {

	private Integer pacienteId;
	private ReporteMedico reporteMedico;
	private String curp;
	private String rfc;
	private String pacienteNombre;
	private String pacienteApellidoPat;
	private String pacienteApellidoMat;
	private String calle;
	private String numero;
	private String colonia;
	private String ciudad;
	private String estado;
	private String telefonoCasa;
	private String celular;
	private String sexo;
	private String ocupacion;
	private Date fechaNac;
	private Set<Citas> citases = new HashSet<Citas>(0);

	public Paciente() {
	}

	public Paciente(ReporteMedico reporteMedico) {
		this.reporteMedico = reporteMedico;
	}

	public Paciente(ReporteMedico reporteMedico, String curp, String rfc,
			String pacienteNombre, String pacienteApellidoPat,
			String pacienteApellidoMat, String calle, String numero,
			String colonia, String ciudad, String estado, String telefonoCasa,
			String celular, String sexo, String ocupacion, Date fechaNac,
			Set<Citas> citases) {
		this.reporteMedico = reporteMedico;
		this.curp = curp;
		this.rfc = rfc;
		this.pacienteNombre = pacienteNombre;
		this.pacienteApellidoPat = pacienteApellidoPat;
		this.pacienteApellidoMat = pacienteApellidoMat;
		this.calle = calle;
		this.numero = numero;
		this.colonia = colonia;
		this.ciudad = ciudad;
		this.estado = estado;
		this.telefonoCasa = telefonoCasa;
		this.celular = celular;
		this.sexo = sexo;
		this.ocupacion = ocupacion;
		this.fechaNac = fechaNac;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paciente_id", unique = true, nullable = false)
	public Integer getPacienteId() {
		return this.pacienteId;
	}

	public void setPacienteId(Integer pacienteId) {
		this.pacienteId = pacienteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reporte_medico_id", nullable = false)
	public ReporteMedico getReporteMedico() {
		return this.reporteMedico;
	}

	public void setReporteMedico(ReporteMedico reporteMedico) {
		this.reporteMedico = reporteMedico;
	}

	@Column(name = "curp", length = 45)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "rfc", length = 45)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "paciente_nombre", length = 45)
	public String getPacienteNombre() {
		return this.pacienteNombre;
	}

	public void setPacienteNombre(String pacienteNombre) {
		this.pacienteNombre = pacienteNombre;
	}

	@Column(name = "paciente_apellido_pat", length = 45)
	public String getPacienteApellidoPat() {
		return this.pacienteApellidoPat;
	}

	public void setPacienteApellidoPat(String pacienteApellidoPat) {
		this.pacienteApellidoPat = pacienteApellidoPat;
	}

	@Column(name = "paciente_apellido_mat", length = 45)
	public String getPacienteApellidoMat() {
		return this.pacienteApellidoMat;
	}

	public void setPacienteApellidoMat(String pacienteApellidoMat) {
		this.pacienteApellidoMat = pacienteApellidoMat;
	}

	@Column(name = "calle", length = 45)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numero", length = 15)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "colonia", length = 45)
	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	@Column(name = "ciudad", length = 45)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "telefono_casa", length = 45)
	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	@Column(name = "celular", length = 45)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "sexo", length = 45)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "ocupacion", length = 45)
	public String getOcupacion() {
		return this.ocupacion;
	}

	public void setOcupacion(String ocupacion) {
		this.ocupacion = ocupacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", length = 0)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}

}
