package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pantallas generated by hbm2java
 */
@Entity
@Table(name = "pantallas", catalog = "clinicadb")
public class Pantallas implements java.io.Serializable {

	private Integer pantallaId;
	private String pantallaNombre;
	private Set<Exclusiones> exclusioneses = new HashSet<Exclusiones>(0);

	public Pantallas() {
	}

	public Pantallas(String pantallaNombre, Set<Exclusiones> exclusioneses) {
		this.pantallaNombre = pantallaNombre;
		this.exclusioneses = exclusioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pantalla_id", unique = true, nullable = false)
	public Integer getPantallaId() {
		return this.pantallaId;
	}

	public void setPantallaId(Integer pantallaId) {
		this.pantallaId = pantallaId;
	}

	@Column(name = "pantalla_nombre", length = 45)
	public String getPantallaNombre() {
		return this.pantallaNombre;
	}

	public void setPantallaNombre(String pantallaNombre) {
		this.pantallaNombre = pantallaNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pantallas")
	public Set<Exclusiones> getExclusioneses() {
		return this.exclusioneses;
	}

	public void setExclusioneses(Set<Exclusiones> exclusioneses) {
		this.exclusioneses = exclusioneses;
	}

}
