package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReporteMedico generated by hbm2java
 */
@Entity
@Table(name = "reporte_medico", catalog = "clinicadb")
public class ReporteMedico implements java.io.Serializable {

	private Integer reporteMedicoId;
	private byte[] padecimientoActual;
	private byte[] exploracionFisica;
	private byte[] laboratorioGabinete;
	private byte[] tratamientosPrevios;
	private byte[] diagnostico;
	private String cicatrices;
	private String ta;
	private String resp;
	private String pulso;
	private String tem;
	private String sao2;
	private String peso;
	private String grupoSanguineo;
	private String vacunacion;
	private Boolean tabaquismo;
	private Boolean alcoholismo;
	private String actDesc;
	private String actDep;
	private Boolean antFamCancer;
	private Boolean antFamCardio;
	private Boolean antFamDiabetes;
	private Boolean antFamObesidad;
	private Boolean antFamEpilepsia;
	private Boolean antFamInmunologicas;
	private Boolean antFamCrisisConvulsivas;
	private Boolean antFamHipertensionArterial;
	private Boolean antFamEndocripatias;
	private Boolean antFamHemopatias;
	private Boolean antFamNeuropatia;
	private Boolean antFamNefropatias;
	private Boolean antFamFracturas;
	private Boolean antFamEnfermMentales;
	private Boolean antFamPsiquiatricas;
	private Boolean antFamEnfermExantemat;
	private Boolean antFamNeumopatias;
	private Boolean antFamTransfusionales;
	private Boolean antFamHospitalizaciones;
	private Boolean antFamCirugias;
	private String antFamOtros;
	private Boolean antPersCancer;
	private Boolean antPersCardio;
	private Boolean antPersDiabetes;
	private Boolean antPersObesidad;
	private Boolean antPersQuirurgicos;
	private Boolean antPersInmunologicas;
	private Boolean antPersAlergias;
	private Boolean antPersCrisisConvulsivas;
	private Boolean antPersHipertensionArterial;
	private Boolean antPersEndocripatias;
	private Boolean antPersHemopatias;
	private Boolean antPersNeuropatias;
	private Boolean antPersNefropatias;
	private Boolean antPersFracturas;
	private Boolean antPersEnfermMentales;
	private Boolean antPersPsiquiatricas;
	private Boolean antPersEnfermExantemat;
	private Boolean antPersNeumopatias;
	private Boolean antPersTransfusionales;
	private Boolean antPersHospitalizaciones;
	private Boolean antPersCirugias;
	private String antPersOtros;
	private Boolean interAparSistLinfatico;
	private Boolean interAparSistCardio;
	private Boolean interAparSistMuscEsquel;
	private Boolean interAparSistDigestivo;
	private Boolean interAparSistUrinario;
	private Boolean interAparSistNervioso;
	private Boolean interAparSistDermatologico;
	private Boolean interAparSistInmunologico;
	private Boolean interAparSistRespiratorio;
	private Set<Paciente> pacientes = new HashSet<Paciente>(0);
	private Set<NotaEvolucion> notaEvolucions = new HashSet<NotaEvolucion>(0);

	public ReporteMedico() {
	}

	public ReporteMedico(byte[] padecimientoActual, byte[] exploracionFisica, byte[] laboratorioGabinete,
			byte[] tratamientosPrevios, byte[] diagnostico, String cicatrices, String ta, String resp, String pulso,
			String tem, String sao2, String peso, String grupoSanguineo, String vacunacion, Boolean tabaquismo,
			Boolean alcoholismo, String actDesc, String actDep, Boolean antFamCancer, Boolean antFamCardio,
			Boolean antFamDiabetes, Boolean antFamObesidad, Boolean antFamEpilepsia, Boolean antFamInmunologicas,
			Boolean antFamCrisisConvulsivas, Boolean antFamHipertensionArterial, Boolean antFamEndocripatias,
			Boolean antFamHemopatias, Boolean antFamNeuropatia, Boolean antFamNefropatias, Boolean antFamFracturas,
			Boolean antFamEnfermMentales, Boolean antFamPsiquiatricas, Boolean antFamEnfermExantemat,
			Boolean antFamNeumopatias, Boolean antFamTransfusionales, Boolean antFamHospitalizaciones,
			Boolean antFamCirugias, String antFamOtros, Boolean antPersCancer, Boolean antPersCardio,
			Boolean antPersDiabetes, Boolean antPersObesidad, Boolean antPersQuirurgicos, Boolean antPersInmunologicas,
			Boolean antPersAlergias, Boolean antPersCrisisConvulsivas, Boolean antPersHipertensionArterial,
			Boolean antPersEndocripatias, Boolean antPersHemopatias, Boolean antPersNeuropatias,
			Boolean antPersNefropatias, Boolean antPersFracturas, Boolean antPersEnfermMentales,
			Boolean antPersPsiquiatricas, Boolean antPersEnfermExantemat, Boolean antPersNeumopatias,
			Boolean antPersTransfusionales, Boolean antPersHospitalizaciones, Boolean antPersCirugias,
			String antPersOtros, Boolean interAparSistLinfatico, Boolean interAparSistCardio,
			Boolean interAparSistMuscEsquel, Boolean interAparSistDigestivo, Boolean interAparSistUrinario,
			Boolean interAparSistNervioso, Boolean interAparSistDermatologico, Boolean interAparSistInmunologico,
			Boolean interAparSistRespiratorio, Set<Paciente> pacientes, Set<NotaEvolucion> notaEvolucions) {
		this.padecimientoActual = padecimientoActual;
		this.exploracionFisica = exploracionFisica;
		this.laboratorioGabinete = laboratorioGabinete;
		this.tratamientosPrevios = tratamientosPrevios;
		this.diagnostico = diagnostico;
		this.cicatrices = cicatrices;
		this.ta = ta;
		this.resp = resp;
		this.pulso = pulso;
		this.tem = tem;
		this.sao2 = sao2;
		this.peso = peso;
		this.grupoSanguineo = grupoSanguineo;
		this.vacunacion = vacunacion;
		this.tabaquismo = tabaquismo;
		this.alcoholismo = alcoholismo;
		this.actDesc = actDesc;
		this.actDep = actDep;
		this.antFamCancer = antFamCancer;
		this.antFamCardio = antFamCardio;
		this.antFamDiabetes = antFamDiabetes;
		this.antFamObesidad = antFamObesidad;
		this.antFamEpilepsia = antFamEpilepsia;
		this.antFamInmunologicas = antFamInmunologicas;
		this.antFamCrisisConvulsivas = antFamCrisisConvulsivas;
		this.antFamHipertensionArterial = antFamHipertensionArterial;
		this.antFamEndocripatias = antFamEndocripatias;
		this.antFamHemopatias = antFamHemopatias;
		this.antFamNeuropatia = antFamNeuropatia;
		this.antFamNefropatias = antFamNefropatias;
		this.antFamFracturas = antFamFracturas;
		this.antFamEnfermMentales = antFamEnfermMentales;
		this.antFamPsiquiatricas = antFamPsiquiatricas;
		this.antFamEnfermExantemat = antFamEnfermExantemat;
		this.antFamNeumopatias = antFamNeumopatias;
		this.antFamTransfusionales = antFamTransfusionales;
		this.antFamHospitalizaciones = antFamHospitalizaciones;
		this.antFamCirugias = antFamCirugias;
		this.antFamOtros = antFamOtros;
		this.antPersCancer = antPersCancer;
		this.antPersCardio = antPersCardio;
		this.antPersDiabetes = antPersDiabetes;
		this.antPersObesidad = antPersObesidad;
		this.antPersQuirurgicos = antPersQuirurgicos;
		this.antPersInmunologicas = antPersInmunologicas;
		this.antPersAlergias = antPersAlergias;
		this.antPersCrisisConvulsivas = antPersCrisisConvulsivas;
		this.antPersHipertensionArterial = antPersHipertensionArterial;
		this.antPersEndocripatias = antPersEndocripatias;
		this.antPersHemopatias = antPersHemopatias;
		this.antPersNeuropatias = antPersNeuropatias;
		this.antPersNefropatias = antPersNefropatias;
		this.antPersFracturas = antPersFracturas;
		this.antPersEnfermMentales = antPersEnfermMentales;
		this.antPersPsiquiatricas = antPersPsiquiatricas;
		this.antPersEnfermExantemat = antPersEnfermExantemat;
		this.antPersNeumopatias = antPersNeumopatias;
		this.antPersTransfusionales = antPersTransfusionales;
		this.antPersHospitalizaciones = antPersHospitalizaciones;
		this.antPersCirugias = antPersCirugias;
		this.antPersOtros = antPersOtros;
		this.interAparSistLinfatico = interAparSistLinfatico;
		this.interAparSistCardio = interAparSistCardio;
		this.interAparSistMuscEsquel = interAparSistMuscEsquel;
		this.interAparSistDigestivo = interAparSistDigestivo;
		this.interAparSistUrinario = interAparSistUrinario;
		this.interAparSistNervioso = interAparSistNervioso;
		this.interAparSistDermatologico = interAparSistDermatologico;
		this.interAparSistInmunologico = interAparSistInmunologico;
		this.interAparSistRespiratorio = interAparSistRespiratorio;
		this.pacientes = pacientes;
		this.notaEvolucions = notaEvolucions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reporte_medico_id", unique = true, nullable = false)
	public Integer getReporteMedicoId() {
		return this.reporteMedicoId;
	}

	public void setReporteMedicoId(Integer reporteMedicoId) {
		this.reporteMedicoId = reporteMedicoId;
	}

	@Column(name = "padecimiento_actual")
	public byte[] getPadecimientoActual() {
		return this.padecimientoActual;
	}

	public void setPadecimientoActual(byte[] padecimientoActual) {
		this.padecimientoActual = padecimientoActual;
	}

	@Column(name = "exploracion_fisica")
	public byte[] getExploracionFisica() {
		return this.exploracionFisica;
	}

	public void setExploracionFisica(byte[] exploracionFisica) {
		this.exploracionFisica = exploracionFisica;
	}

	@Column(name = "laboratorio_gabinete")
	public byte[] getLaboratorioGabinete() {
		return this.laboratorioGabinete;
	}

	public void setLaboratorioGabinete(byte[] laboratorioGabinete) {
		this.laboratorioGabinete = laboratorioGabinete;
	}

	@Column(name = "tratamientos_previos")
	public byte[] getTratamientosPrevios() {
		return this.tratamientosPrevios;
	}

	public void setTratamientosPrevios(byte[] tratamientosPrevios) {
		this.tratamientosPrevios = tratamientosPrevios;
	}

	@Column(name = "diagnostico")
	public byte[] getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(byte[] diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "cicatrices", length = 45)
	public String getCicatrices() {
		return this.cicatrices;
	}

	public void setCicatrices(String cicatrices) {
		this.cicatrices = cicatrices;
	}

	@Column(name = "TA", length = 8)
	public String getTa() {
		return this.ta;
	}

	public void setTa(String ta) {
		this.ta = ta;
	}

	@Column(name = "RESP", length = 3)
	public String getResp() {
		return this.resp;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}

	@Column(name = "pulso", length = 3)
	public String getPulso() {
		return this.pulso;
	}

	public void setPulso(String pulso) {
		this.pulso = pulso;
	}

	@Column(name = "TEM", length = 5)
	public String getTem() {
		return this.tem;
	}

	public void setTem(String tem) {
		this.tem = tem;
	}

	@Column(name = "SAO2", length = 3)
	public String getSao2() {
		return this.sao2;
	}

	public void setSao2(String sao2) {
		this.sao2 = sao2;
	}

	@Column(name = "peso", length = 3)
	public String getPeso() {
		return this.peso;
	}

	public void setPeso(String peso) {
		this.peso = peso;
	}

	@Column(name = "grupo_sanguineo", length = 3)
	public String getGrupoSanguineo() {
		return this.grupoSanguineo;
	}

	public void setGrupoSanguineo(String grupoSanguineo) {
		this.grupoSanguineo = grupoSanguineo;
	}

	@Column(name = "vacunacion", length = 15)
	public String getVacunacion() {
		return this.vacunacion;
	}

	public void setVacunacion(String vacunacion) {
		this.vacunacion = vacunacion;
	}

	@Column(name = "tabaquismo")
	public Boolean getTabaquismo() {
		return this.tabaquismo;
	}

	public void setTabaquismo(Boolean tabaquismo) {
		this.tabaquismo = tabaquismo;
	}

	@Column(name = "alcoholismo")
	public Boolean getAlcoholismo() {
		return this.alcoholismo;
	}

	public void setAlcoholismo(Boolean alcoholismo) {
		this.alcoholismo = alcoholismo;
	}

	@Column(name = "act_desc", length = 15)
	public String getActDesc() {
		return this.actDesc;
	}

	public void setActDesc(String actDesc) {
		this.actDesc = actDesc;
	}

	@Column(name = "act_dep", length = 15)
	public String getActDep() {
		return this.actDep;
	}

	public void setActDep(String actDep) {
		this.actDep = actDep;
	}

	@Column(name = "ant_fam_cancer")
	public Boolean getAntFamCancer() {
		return this.antFamCancer;
	}

	public void setAntFamCancer(Boolean antFamCancer) {
		this.antFamCancer = antFamCancer;
	}

	@Column(name = "ant_fam_cardio")
	public Boolean getAntFamCardio() {
		return this.antFamCardio;
	}

	public void setAntFamCardio(Boolean antFamCardio) {
		this.antFamCardio = antFamCardio;
	}

	@Column(name = "ant_fam_diabetes")
	public Boolean getAntFamDiabetes() {
		return this.antFamDiabetes;
	}

	public void setAntFamDiabetes(Boolean antFamDiabetes) {
		this.antFamDiabetes = antFamDiabetes;
	}

	@Column(name = "ant_fam_obesidad")
	public Boolean getAntFamObesidad() {
		return this.antFamObesidad;
	}

	public void setAntFamObesidad(Boolean antFamObesidad) {
		this.antFamObesidad = antFamObesidad;
	}

	@Column(name = "ant_fam_epilepsia")
	public Boolean getAntFamEpilepsia() {
		return this.antFamEpilepsia;
	}

	public void setAntFamEpilepsia(Boolean antFamEpilepsia) {
		this.antFamEpilepsia = antFamEpilepsia;
	}

	@Column(name = "ant_fam_inmunologicas")
	public Boolean getAntFamInmunologicas() {
		return this.antFamInmunologicas;
	}

	public void setAntFamInmunologicas(Boolean antFamInmunologicas) {
		this.antFamInmunologicas = antFamInmunologicas;
	}

	@Column(name = "ant_fam_crisis_convulsivas")
	public Boolean getAntFamCrisisConvulsivas() {
		return this.antFamCrisisConvulsivas;
	}

	public void setAntFamCrisisConvulsivas(Boolean antFamCrisisConvulsivas) {
		this.antFamCrisisConvulsivas = antFamCrisisConvulsivas;
	}

	@Column(name = "ant_fam_hipertension_arterial")
	public Boolean getAntFamHipertensionArterial() {
		return this.antFamHipertensionArterial;
	}

	public void setAntFamHipertensionArterial(Boolean antFamHipertensionArterial) {
		this.antFamHipertensionArterial = antFamHipertensionArterial;
	}

	@Column(name = "ant_fam_endocripatias")
	public Boolean getAntFamEndocripatias() {
		return this.antFamEndocripatias;
	}

	public void setAntFamEndocripatias(Boolean antFamEndocripatias) {
		this.antFamEndocripatias = antFamEndocripatias;
	}

	@Column(name = "ant_fam_hemopatias")
	public Boolean getAntFamHemopatias() {
		return this.antFamHemopatias;
	}

	public void setAntFamHemopatias(Boolean antFamHemopatias) {
		this.antFamHemopatias = antFamHemopatias;
	}

	@Column(name = "ant_fam_neuropatia")
	public Boolean getAntFamNeuropatia() {
		return this.antFamNeuropatia;
	}

	public void setAntFamNeuropatia(Boolean antFamNeuropatia) {
		this.antFamNeuropatia = antFamNeuropatia;
	}

	@Column(name = "ant_fam_nefropatias")
	public Boolean getAntFamNefropatias() {
		return this.antFamNefropatias;
	}

	public void setAntFamNefropatias(Boolean antFamNefropatias) {
		this.antFamNefropatias = antFamNefropatias;
	}

	@Column(name = "ant_fam_fracturas")
	public Boolean getAntFamFracturas() {
		return this.antFamFracturas;
	}

	public void setAntFamFracturas(Boolean antFamFracturas) {
		this.antFamFracturas = antFamFracturas;
	}

	@Column(name = "ant_fam_enferm_mentales")
	public Boolean getAntFamEnfermMentales() {
		return this.antFamEnfermMentales;
	}

	public void setAntFamEnfermMentales(Boolean antFamEnfermMentales) {
		this.antFamEnfermMentales = antFamEnfermMentales;
	}

	@Column(name = "ant_fam_psiquiatricas")
	public Boolean getAntFamPsiquiatricas() {
		return this.antFamPsiquiatricas;
	}

	public void setAntFamPsiquiatricas(Boolean antFamPsiquiatricas) {
		this.antFamPsiquiatricas = antFamPsiquiatricas;
	}

	@Column(name = "ant_fam_enferm_exantemat")
	public Boolean getAntFamEnfermExantemat() {
		return this.antFamEnfermExantemat;
	}

	public void setAntFamEnfermExantemat(Boolean antFamEnfermExantemat) {
		this.antFamEnfermExantemat = antFamEnfermExantemat;
	}

	@Column(name = "ant_fam_neumopatias")
	public Boolean getAntFamNeumopatias() {
		return this.antFamNeumopatias;
	}

	public void setAntFamNeumopatias(Boolean antFamNeumopatias) {
		this.antFamNeumopatias = antFamNeumopatias;
	}

	@Column(name = "ant_fam_transfusionales")
	public Boolean getAntFamTransfusionales() {
		return this.antFamTransfusionales;
	}

	public void setAntFamTransfusionales(Boolean antFamTransfusionales) {
		this.antFamTransfusionales = antFamTransfusionales;
	}

	@Column(name = "ant_fam_hospitalizaciones")
	public Boolean getAntFamHospitalizaciones() {
		return this.antFamHospitalizaciones;
	}

	public void setAntFamHospitalizaciones(Boolean antFamHospitalizaciones) {
		this.antFamHospitalizaciones = antFamHospitalizaciones;
	}

	@Column(name = "ant_fam_cirugias")
	public Boolean getAntFamCirugias() {
		return this.antFamCirugias;
	}

	public void setAntFamCirugias(Boolean antFamCirugias) {
		this.antFamCirugias = antFamCirugias;
	}

	@Column(name = "ant_fam_otros", length = 45)
	public String getAntFamOtros() {
		return this.antFamOtros;
	}

	public void setAntFamOtros(String antFamOtros) {
		this.antFamOtros = antFamOtros;
	}

	@Column(name = "ant_pers_cancer")
	public Boolean getAntPersCancer() {
		return this.antPersCancer;
	}

	public void setAntPersCancer(Boolean antPersCancer) {
		this.antPersCancer = antPersCancer;
	}

	@Column(name = "ant_pers_cardio")
	public Boolean getAntPersCardio() {
		return this.antPersCardio;
	}

	public void setAntPersCardio(Boolean antPersCardio) {
		this.antPersCardio = antPersCardio;
	}

	@Column(name = "ant_pers_diabetes")
	public Boolean getAntPersDiabetes() {
		return this.antPersDiabetes;
	}

	public void setAntPersDiabetes(Boolean antPersDiabetes) {
		this.antPersDiabetes = antPersDiabetes;
	}

	@Column(name = "ant_pers_obesidad")
	public Boolean getAntPersObesidad() {
		return this.antPersObesidad;
	}

	public void setAntPersObesidad(Boolean antPersObesidad) {
		this.antPersObesidad = antPersObesidad;
	}

	@Column(name = "ant_pers_quirurgicos")
	public Boolean getAntPersQuirurgicos() {
		return this.antPersQuirurgicos;
	}

	public void setAntPersQuirurgicos(Boolean antPersQuirurgicos) {
		this.antPersQuirurgicos = antPersQuirurgicos;
	}

	@Column(name = "ant_pers_inmunologicas")
	public Boolean getAntPersInmunologicas() {
		return this.antPersInmunologicas;
	}

	public void setAntPersInmunologicas(Boolean antPersInmunologicas) {
		this.antPersInmunologicas = antPersInmunologicas;
	}

	@Column(name = "ant_pers_alergias")
	public Boolean getAntPersAlergias() {
		return this.antPersAlergias;
	}

	public void setAntPersAlergias(Boolean antPersAlergias) {
		this.antPersAlergias = antPersAlergias;
	}

	@Column(name = "ant_pers_crisis_convulsivas")
	public Boolean getAntPersCrisisConvulsivas() {
		return this.antPersCrisisConvulsivas;
	}

	public void setAntPersCrisisConvulsivas(Boolean antPersCrisisConvulsivas) {
		this.antPersCrisisConvulsivas = antPersCrisisConvulsivas;
	}

	@Column(name = "ant_pers_hipertension_arterial")
	public Boolean getAntPersHipertensionArterial() {
		return this.antPersHipertensionArterial;
	}

	public void setAntPersHipertensionArterial(Boolean antPersHipertensionArterial) {
		this.antPersHipertensionArterial = antPersHipertensionArterial;
	}

	@Column(name = "ant_pers_endocripatias")
	public Boolean getAntPersEndocripatias() {
		return this.antPersEndocripatias;
	}

	public void setAntPersEndocripatias(Boolean antPersEndocripatias) {
		this.antPersEndocripatias = antPersEndocripatias;
	}

	@Column(name = "ant_pers_hemopatias")
	public Boolean getAntPersHemopatias() {
		return this.antPersHemopatias;
	}

	public void setAntPersHemopatias(Boolean antPersHemopatias) {
		this.antPersHemopatias = antPersHemopatias;
	}

	@Column(name = "ant_pers_neuropatias")
	public Boolean getAntPersNeuropatias() {
		return this.antPersNeuropatias;
	}

	public void setAntPersNeuropatias(Boolean antPersNeuropatias) {
		this.antPersNeuropatias = antPersNeuropatias;
	}

	@Column(name = "ant_pers_nefropatias")
	public Boolean getAntPersNefropatias() {
		return this.antPersNefropatias;
	}

	public void setAntPersNefropatias(Boolean antPersNefropatias) {
		this.antPersNefropatias = antPersNefropatias;
	}

	@Column(name = "ant_pers_fracturas")
	public Boolean getAntPersFracturas() {
		return this.antPersFracturas;
	}

	public void setAntPersFracturas(Boolean antPersFracturas) {
		this.antPersFracturas = antPersFracturas;
	}

	@Column(name = "ant_pers_enferm_mentales")
	public Boolean getAntPersEnfermMentales() {
		return this.antPersEnfermMentales;
	}

	public void setAntPersEnfermMentales(Boolean antPersEnfermMentales) {
		this.antPersEnfermMentales = antPersEnfermMentales;
	}

	@Column(name = "ant_pers_psiquiatricas")
	public Boolean getAntPersPsiquiatricas() {
		return this.antPersPsiquiatricas;
	}

	public void setAntPersPsiquiatricas(Boolean antPersPsiquiatricas) {
		this.antPersPsiquiatricas = antPersPsiquiatricas;
	}

	@Column(name = "ant_pers_enferm_exantemat")
	public Boolean getAntPersEnfermExantemat() {
		return this.antPersEnfermExantemat;
	}

	public void setAntPersEnfermExantemat(Boolean antPersEnfermExantemat) {
		this.antPersEnfermExantemat = antPersEnfermExantemat;
	}

	@Column(name = "ant_pers_neumopatias")
	public Boolean getAntPersNeumopatias() {
		return this.antPersNeumopatias;
	}

	public void setAntPersNeumopatias(Boolean antPersNeumopatias) {
		this.antPersNeumopatias = antPersNeumopatias;
	}

	@Column(name = "ant_pers_transfusionales")
	public Boolean getAntPersTransfusionales() {
		return this.antPersTransfusionales;
	}

	public void setAntPersTransfusionales(Boolean antPersTransfusionales) {
		this.antPersTransfusionales = antPersTransfusionales;
	}

	@Column(name = "ant_pers_hospitalizaciones")
	public Boolean getAntPersHospitalizaciones() {
		return this.antPersHospitalizaciones;
	}

	public void setAntPersHospitalizaciones(Boolean antPersHospitalizaciones) {
		this.antPersHospitalizaciones = antPersHospitalizaciones;
	}

	@Column(name = "ant_pers_cirugias")
	public Boolean getAntPersCirugias() {
		return this.antPersCirugias;
	}

	public void setAntPersCirugias(Boolean antPersCirugias) {
		this.antPersCirugias = antPersCirugias;
	}

	@Column(name = "ant_pers_otros", length = 45)
	public String getAntPersOtros() {
		return this.antPersOtros;
	}

	public void setAntPersOtros(String antPersOtros) {
		this.antPersOtros = antPersOtros;
	}

	@Column(name = "inter_apar_sist_linfatico")
	public Boolean getInterAparSistLinfatico() {
		return this.interAparSistLinfatico;
	}

	public void setInterAparSistLinfatico(Boolean interAparSistLinfatico) {
		this.interAparSistLinfatico = interAparSistLinfatico;
	}

	@Column(name = "inter_apar_sist_cardio")
	public Boolean getInterAparSistCardio() {
		return this.interAparSistCardio;
	}

	public void setInterAparSistCardio(Boolean interAparSistCardio) {
		this.interAparSistCardio = interAparSistCardio;
	}

	@Column(name = "inter_apar_sist_musc_esquel")
	public Boolean getInterAparSistMuscEsquel() {
		return this.interAparSistMuscEsquel;
	}

	public void setInterAparSistMuscEsquel(Boolean interAparSistMuscEsquel) {
		this.interAparSistMuscEsquel = interAparSistMuscEsquel;
	}

	@Column(name = "inter_apar_sist_digestivo")
	public Boolean getInterAparSistDigestivo() {
		return this.interAparSistDigestivo;
	}

	public void setInterAparSistDigestivo(Boolean interAparSistDigestivo) {
		this.interAparSistDigestivo = interAparSistDigestivo;
	}

	@Column(name = "inter_apar_sist_urinario")
	public Boolean getInterAparSistUrinario() {
		return this.interAparSistUrinario;
	}

	public void setInterAparSistUrinario(Boolean interAparSistUrinario) {
		this.interAparSistUrinario = interAparSistUrinario;
	}

	@Column(name = "inter_apar_sist_nervioso")
	public Boolean getInterAparSistNervioso() {
		return this.interAparSistNervioso;
	}

	public void setInterAparSistNervioso(Boolean interAparSistNervioso) {
		this.interAparSistNervioso = interAparSistNervioso;
	}

	@Column(name = "inter_apar_sist_dermatologico")
	public Boolean getInterAparSistDermatologico() {
		return this.interAparSistDermatologico;
	}

	public void setInterAparSistDermatologico(Boolean interAparSistDermatologico) {
		this.interAparSistDermatologico = interAparSistDermatologico;
	}

	@Column(name = "inter_apar_sist_inmunologico")
	public Boolean getInterAparSistInmunologico() {
		return this.interAparSistInmunologico;
	}

	public void setInterAparSistInmunologico(Boolean interAparSistInmunologico) {
		this.interAparSistInmunologico = interAparSistInmunologico;
	}

	@Column(name = "inter_apar_sist_respiratorio")
	public Boolean getInterAparSistRespiratorio() {
		return this.interAparSistRespiratorio;
	}

	public void setInterAparSistRespiratorio(Boolean interAparSistRespiratorio) {
		this.interAparSistRespiratorio = interAparSistRespiratorio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteMedico")
	public Set<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Set<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteMedico")
	public Set<NotaEvolucion> getNotaEvolucions() {
		return this.notaEvolucions;
	}

	public void setNotaEvolucions(Set<NotaEvolucion> notaEvolucions) {
		this.notaEvolucions = notaEvolucions;
	}

}
