package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "clinicadb")
public class Role implements java.io.Serializable {

	private int roleId;
	private String code;
	private Set<Exclusiones> exclusioneses = new HashSet<Exclusiones>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Role() {
	}

	public Role(int roleId) {
		this.roleId = roleId;
	}

	public Role(int roleId, String code, Set<Exclusiones> exclusioneses, Set<Usuario> usuarios) {
		this.roleId = roleId;
		this.code = code;
		this.exclusioneses = exclusioneses;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "code", length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Exclusiones> getExclusioneses() {
		return this.exclusioneses;
	}

	public void setExclusioneses(Set<Exclusiones> exclusioneses) {
		this.exclusioneses = exclusioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
