package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tratamiento generated by hbm2java
 */
@Entity
@Table(name = "tratamiento", catalog = "clinicadb")
public class Tratamiento implements java.io.Serializable {

	private Integer tratamientoId;
	private String tratamientoNombre;
	private Long precio;
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);
	private Set<Cita> citas = new HashSet<Cita>(0);
	private Set<HabitacionNota> habitacionNotas = new HashSet<HabitacionNota>(0);

	public Tratamiento() {
	}

	public Tratamiento(String tratamientoNombre, Long precio, Set<VentaDiaria> ventaDiarias, Set<Cita> citas,
			Set<HabitacionNota> habitacionNotas) {
		this.tratamientoNombre = tratamientoNombre;
		this.precio = precio;
		this.ventaDiarias = ventaDiarias;
		this.citas = citas;
		this.habitacionNotas = habitacionNotas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tratamiento_id", unique = true, nullable = false)
	public Integer getTratamientoId() {
		return this.tratamientoId;
	}

	public void setTratamientoId(Integer tratamientoId) {
		this.tratamientoId = tratamientoId;
	}

	@Column(name = "tratamiento_nombre", length = 45)
	public String getTratamientoNombre() {
		return this.tratamientoNombre;
	}

	public void setTratamientoNombre(String tratamientoNombre) {
		this.tratamientoNombre = tratamientoNombre;
	}

	@Column(name = "precio", precision = 10, scale = 0)
	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tratamiento")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tratamientos")
	public Set<Cita> getCitas() {
		return this.citas;
	}

	public void setCitas(Set<Cita> citas) {
		this.citas = citas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tratamiento")
	public Set<HabitacionNota> getHabitacionNotas() {
		return this.habitacionNotas;
	}

	public void setHabitacionNotas(Set<HabitacionNota> habitacionNotas) {
		this.habitacionNotas = habitacionNotas;
	}

}
