package com.sanantial.entity;

// Generated Dec 30, 2013 5:02:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tratamiento generated by hbm2java
 */
@Entity
@Table(name = "tratamiento", catalog = "sanantialdb")
public class Tratamiento implements java.io.Serializable {

	private Integer tratamientoId;
	private String tratamientoNombre;
	private Long precio;
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);
	private Set<Citas> citases = new HashSet<Citas>(0);

	public Tratamiento() {
	}

	public Tratamiento(String tratamientoNombre, Long precio,
			Set<VentaDiaria> ventaDiarias, Set<Citas> citases) {
		this.tratamientoNombre = tratamientoNombre;
		this.precio = precio;
		this.ventaDiarias = ventaDiarias;
		this.citases = citases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tratamiento_id", unique = true, nullable = false)
	public Integer getTratamientoId() {
		return this.tratamientoId;
	}

	public void setTratamientoId(Integer tratamientoId) {
		this.tratamientoId = tratamientoId;
	}

	@Column(name = "tratamiento_nombre", length = 45)
	public String getTratamientoNombre() {
		return this.tratamientoNombre;
	}

	public void setTratamientoNombre(String tratamientoNombre) {
		this.tratamientoNombre = tratamientoNombre;
	}

	@Column(name = "precio", precision = 10, scale = 0)
	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tratamiento")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tratamientos")
	public Set<Citas> getCitases() {
		return this.citases;
	}

	public void setCitases(Set<Citas> citases) {
		this.citases = citases;
	}
	
	public boolean equals(Object o) {
			if ((o instanceof Tratamiento) && (((Tratamiento)o).getTratamientoId()== this.tratamientoId)) {
				return true;
			} else {
				return false;
			}
		}

}
