package com.sanantial.entity;
// Generated 02-ene-2017 20:51:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "clinicadb")
public class Usuario implements java.io.Serializable {

	private Integer usuarioId;
	private Role role;
	private String usuarioNombre;
	private String password;
	private Set<VentaDiaria> ventaDiarias = new HashSet<VentaDiaria>(0);
	private Set<GastoDiario> gastoDiarios = new HashSet<GastoDiario>(0);
	private Set<IngresoDiario> ingresoDiarios = new HashSet<IngresoDiario>(0);

	public Usuario() {
	}

	public Usuario(Role role) {
		this.role = role;
	}

	public Usuario(Role role, String usuarioNombre, String password, Set<VentaDiaria> ventaDiarias,
			Set<GastoDiario> gastoDiarios, Set<IngresoDiario> ingresoDiarios) {
		this.role = role;
		this.usuarioNombre = usuarioNombre;
		this.password = password;
		this.ventaDiarias = ventaDiarias;
		this.gastoDiarios = gastoDiarios;
		this.ingresoDiarios = ingresoDiarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usuario_id", unique = true, nullable = false)
	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "usuario_nombre", length = 45)
	public String getUsuarioNombre() {
		return this.usuarioNombre;
	}

	public void setUsuarioNombre(String usuarioNombre) {
		this.usuarioNombre = usuarioNombre;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<VentaDiaria> getVentaDiarias() {
		return this.ventaDiarias;
	}

	public void setVentaDiarias(Set<VentaDiaria> ventaDiarias) {
		this.ventaDiarias = ventaDiarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<GastoDiario> getGastoDiarios() {
		return this.gastoDiarios;
	}

	public void setGastoDiarios(Set<GastoDiario> gastoDiarios) {
		this.gastoDiarios = gastoDiarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<IngresoDiario> getIngresoDiarios() {
		return this.ingresoDiarios;
	}

	public void setIngresoDiarios(Set<IngresoDiario> ingresoDiarios) {
		this.ingresoDiarios = ingresoDiarios;
	}

}
