package com.sanantial.entity;

// Generated Jan 11, 2014 3:42:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VentaDiaria generated by hbm2java
 */
@Entity
@Table(name = "venta_diaria", catalog = "sanantialdb")
public class VentaDiaria implements java.io.Serializable {

	private Integer ventaId;
	private Consulta consulta;
	private Tratamiento tratamiento;
	private Medicamento medicamento;
	private Usuario usuario;
	private NotaVenta notaVenta;
	private Integer descuento;
	private Integer vale;
	private Integer cantidad;
	private Long pagoTarjeta;
	private Date fecha;

	public VentaDiaria() {
	}

	public VentaDiaria(Consulta consulta, Tratamiento tratamiento,
			Medicamento medicamento, Usuario usuario, NotaVenta notaVenta) {
		this.consulta = consulta;
		this.tratamiento = tratamiento;
		this.medicamento = medicamento;
		this.usuario = usuario;
		this.notaVenta = notaVenta;
	}

	public VentaDiaria(Consulta consulta, Tratamiento tratamiento,
			Medicamento medicamento, Usuario usuario, NotaVenta notaVenta,
			Integer descuento, Integer vale, Long pagoTarjeta, Integer cantidad, Date fecha) {
		this.consulta = consulta;
		this.tratamiento = tratamiento;
		this.medicamento = medicamento;
		this.usuario = usuario;
		this.notaVenta = notaVenta;
		this.descuento = descuento;
		this.vale = vale;
		this.pagoTarjeta = pagoTarjeta;
		this.cantidad=cantidad;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "venta_id", unique = true, nullable = false)
	public Integer getVentaId() {
		return this.ventaId;
	}

	public void setVentaId(Integer ventaId) {
		this.ventaId = ventaId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consulta_id", nullable = false)
	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tratamiento_id", nullable = false)
	public Tratamiento getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(Tratamiento tratamiento) {
		this.tratamiento = tratamiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicamento_id", nullable = false)
	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(Medicamento medicamento) {
		this.medicamento = medicamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nota_venta_id", nullable = false)
	public NotaVenta getNotaVenta() {
		return this.notaVenta;
	}

	public void setNotaVenta(NotaVenta notaVenta) {
		this.notaVenta = notaVenta;
	}

	@Column(name = "descuento")
	public Integer getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Integer descuento) {
		this.descuento = descuento;
	}

	@Column(name = "vale")
	public Integer getVale() {
		return this.vale;
	}

	public void setVale(Integer vale) {
		this.vale = vale;
	}

	@Column(name = "pago_tarjeta", precision = 10, scale = 0)
	public Long getPagoTarjeta() {
		return this.pagoTarjeta;
	}

	public void setPagoTarjeta(Long pagoTarjeta) {
		this.pagoTarjeta = pagoTarjeta;
	}
	
	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
